//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class master {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal master() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.master", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy From Outgoing Agent.
        /// </summary>
        internal static string clientCopyFormOutgoingAgent {
            get {
                return ResourceManager.GetString("clientCopyFormOutgoingAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy From Instructor.
        /// </summary>
        internal static string clientCopyFormReferer {
            get {
                return ResourceManager.GetString("clientCopyFormReferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string clientRemarks {
            get {
                return ResourceManager.GetString("clientRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Group.
        /// </summary>
        internal static string client_accountGroup {
            get {
                return ResourceManager.GetString("client_accountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        internal static string client_billingAddressFirst {
            get {
                return ResourceManager.GetString("client_billingAddressFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string client_billingAddressSecond {
            get {
                return ResourceManager.GetString("client_billingAddressSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Email.
        /// </summary>
        internal static string client_billingEmail {
            get {
                return ResourceManager.GetString("client_billingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        internal static string client_clientName {
            get {
                return ResourceManager.GetString("client_clientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client No..
        /// </summary>
        internal static string client_clientNum {
            get {
                return ResourceManager.GetString("client_clientNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string client_contactPerson {
            get {
                return ResourceManager.GetString("client_contactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 02.
        /// </summary>
        internal static string client_contactPerson02 {
            get {
                return ResourceManager.GetString("client_contactPerson02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 03.
        /// </summary>
        internal static string client_contactPerson03 {
            get {
                return ResourceManager.GetString("client_contactPerson03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 04.
        /// </summary>
        internal static string client_contactPerson04 {
            get {
                return ResourceManager.GetString("client_contactPerson04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 05.
        /// </summary>
        internal static string client_contactPerson05 {
            get {
                return ResourceManager.GetString("client_contactPerson05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 06.
        /// </summary>
        internal static string client_contactPerson06 {
            get {
                return ResourceManager.GetString("client_contactPerson06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 07.
        /// </summary>
        internal static string client_contactPerson07 {
            get {
                return ResourceManager.GetString("client_contactPerson07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 08.
        /// </summary>
        internal static string client_contactPerson08 {
            get {
                return ResourceManager.GetString("client_contactPerson08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 09.
        /// </summary>
        internal static string client_contactPerson09 {
            get {
                return ResourceManager.GetString("client_contactPerson09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 10.
        /// </summary>
        internal static string client_contactPerson10 {
            get {
                return ResourceManager.GetString("client_contactPerson10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 11.
        /// </summary>
        internal static string client_contactPerson11 {
            get {
                return ResourceManager.GetString("client_contactPerson11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 12.
        /// </summary>
        internal static string client_contactPerson12 {
            get {
                return ResourceManager.GetString("client_contactPerson12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 13.
        /// </summary>
        internal static string client_contactPerson13 {
            get {
                return ResourceManager.GetString("client_contactPerson13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 14.
        /// </summary>
        internal static string client_contactPerson14 {
            get {
                return ResourceManager.GetString("client_contactPerson14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 15.
        /// </summary>
        internal static string client_contactPerson15 {
            get {
                return ResourceManager.GetString("client_contactPerson15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 16.
        /// </summary>
        internal static string client_contactPerson16 {
            get {
                return ResourceManager.GetString("client_contactPerson16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 17.
        /// </summary>
        internal static string client_contactPerson17 {
            get {
                return ResourceManager.GetString("client_contactPerson17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 18.
        /// </summary>
        internal static string client_contactPerson18 {
            get {
                return ResourceManager.GetString("client_contactPerson18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 19.
        /// </summary>
        internal static string client_contactPerson19 {
            get {
                return ResourceManager.GetString("client_contactPerson19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 20.
        /// </summary>
        internal static string client_contactPerson20 {
            get {
                return ResourceManager.GetString("client_contactPerson20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence Address 1.
        /// </summary>
        internal static string client_correspondingAddress1First {
            get {
                return ResourceManager.GetString("client_correspondingAddress1First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string client_correspondingAddress1Second {
            get {
                return ResourceManager.GetString("client_correspondingAddress1Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence Address 2.
        /// </summary>
        internal static string client_correspondingAddress2First {
            get {
                return ResourceManager.GetString("client_correspondingAddress2First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string client_correspondingAddress2Second {
            get {
                return ResourceManager.GetString("client_correspondingAddress2Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount(%).
        /// </summary>
        internal static string client_discount {
            get {
                return ResourceManager.GetString("client_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string client_email {
            get {
                return ResourceManager.GetString("client_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 02.
        /// </summary>
        internal static string client_email02 {
            get {
                return ResourceManager.GetString("client_email02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 03.
        /// </summary>
        internal static string client_email03 {
            get {
                return ResourceManager.GetString("client_email03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 04.
        /// </summary>
        internal static string client_email04 {
            get {
                return ResourceManager.GetString("client_email04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 05.
        /// </summary>
        internal static string client_email05 {
            get {
                return ResourceManager.GetString("client_email05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 06.
        /// </summary>
        internal static string client_email06 {
            get {
                return ResourceManager.GetString("client_email06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 07.
        /// </summary>
        internal static string client_email07 {
            get {
                return ResourceManager.GetString("client_email07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 08.
        /// </summary>
        internal static string client_email08 {
            get {
                return ResourceManager.GetString("client_email08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 09.
        /// </summary>
        internal static string client_email09 {
            get {
                return ResourceManager.GetString("client_email09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 10.
        /// </summary>
        internal static string client_email10 {
            get {
                return ResourceManager.GetString("client_email10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 11.
        /// </summary>
        internal static string client_email11 {
            get {
                return ResourceManager.GetString("client_email11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 12.
        /// </summary>
        internal static string client_email12 {
            get {
                return ResourceManager.GetString("client_email12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 13.
        /// </summary>
        internal static string client_email13 {
            get {
                return ResourceManager.GetString("client_email13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 14.
        /// </summary>
        internal static string client_email14 {
            get {
                return ResourceManager.GetString("client_email14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 15.
        /// </summary>
        internal static string client_email15 {
            get {
                return ResourceManager.GetString("client_email15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 16.
        /// </summary>
        internal static string client_email16 {
            get {
                return ResourceManager.GetString("client_email16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 17.
        /// </summary>
        internal static string client_email17 {
            get {
                return ResourceManager.GetString("client_email17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 18.
        /// </summary>
        internal static string client_email18 {
            get {
                return ResourceManager.GetString("client_email18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 19.
        /// </summary>
        internal static string client_email19 {
            get {
                return ResourceManager.GetString("client_email19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 20.
        /// </summary>
        internal static string client_email20 {
            get {
                return ResourceManager.GetString("client_email20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string client_fax {
            get {
                return ResourceManager.GetString("client_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO No.
        /// </summary>
        internal static string client_ioNumOfReferer {
            get {
                return ResourceManager.GetString("client_ioNumOfReferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release To Public.
        /// </summary>
        internal static string client_isReleaseToPublic {
            get {
                return ResourceManager.GetString("client_isReleaseToPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        internal static string client_Referer {
            get {
                return ResourceManager.GetString("client_Referer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref No.
        /// </summary>
        internal static string client_refNumOfReferer {
            get {
                return ResourceManager.GetString("client_refNumOfReferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string client_tel {
            get {
                return ResourceManager.GetString("client_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 02.
        /// </summary>
        internal static string client_tel02 {
            get {
                return ResourceManager.GetString("client_tel02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 03.
        /// </summary>
        internal static string client_tel03 {
            get {
                return ResourceManager.GetString("client_tel03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 04.
        /// </summary>
        internal static string client_tel04 {
            get {
                return ResourceManager.GetString("client_tel04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 05.
        /// </summary>
        internal static string client_tel05 {
            get {
                return ResourceManager.GetString("client_tel05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 06.
        /// </summary>
        internal static string client_tel06 {
            get {
                return ResourceManager.GetString("client_tel06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 07.
        /// </summary>
        internal static string client_tel07 {
            get {
                return ResourceManager.GetString("client_tel07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 08.
        /// </summary>
        internal static string client_tel08 {
            get {
                return ResourceManager.GetString("client_tel08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 09.
        /// </summary>
        internal static string client_tel09 {
            get {
                return ResourceManager.GetString("client_tel09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 10.
        /// </summary>
        internal static string client_tel10 {
            get {
                return ResourceManager.GetString("client_tel10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 11.
        /// </summary>
        internal static string client_tel11 {
            get {
                return ResourceManager.GetString("client_tel11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 12.
        /// </summary>
        internal static string client_tel12 {
            get {
                return ResourceManager.GetString("client_tel12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 13.
        /// </summary>
        internal static string client_tel13 {
            get {
                return ResourceManager.GetString("client_tel13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 14.
        /// </summary>
        internal static string client_tel14 {
            get {
                return ResourceManager.GetString("client_tel14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 15.
        /// </summary>
        internal static string client_tel15 {
            get {
                return ResourceManager.GetString("client_tel15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 16.
        /// </summary>
        internal static string client_tel16 {
            get {
                return ResourceManager.GetString("client_tel16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 17.
        /// </summary>
        internal static string client_tel17 {
            get {
                return ResourceManager.GetString("client_tel17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 18.
        /// </summary>
        internal static string client_tel18 {
            get {
                return ResourceManager.GetString("client_tel18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 19.
        /// </summary>
        internal static string client_tel19 {
            get {
                return ResourceManager.GetString("client_tel19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 20.
        /// </summary>
        internal static string client_tel20 {
            get {
                return ResourceManager.GetString("client_tel20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Name.
        /// </summary>
        internal static string client_UpdateByUserName {
            get {
                return ResourceManager.GetString("client_UpdateByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date.
        /// </summary>
        internal static string client_UpdateDate {
            get {
                return ResourceManager.GetString("client_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        internal static string currency_currencyName {
            get {
                return ResourceManager.GetString("currency_currencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate To HKD.
        /// </summary>
        internal static string currency_rateToHK {
            get {
                return ResourceManager.GetString("currency_rateToHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string currency_symbol {
            get {
                return ResourceManager.GetString("currency_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string keyword_description {
            get {
                return ResourceManager.GetString("keyword_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string keyword_name {
            get {
                return ResourceManager.GetString("keyword_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        internal static string otherparties_billingAddressFirst {
            get {
                return ResourceManager.GetString("otherparties_billingAddressFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string otherparties_billingAddressSecond {
            get {
                return ResourceManager.GetString("otherparties_billingAddressSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string otherparties_contactPerson {
            get {
                return ResourceManager.GetString("otherparties_contactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence Address 1.
        /// </summary>
        internal static string otherparties_correspondingAddress1First {
            get {
                return ResourceManager.GetString("otherparties_correspondingAddress1First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string otherparties_correspondingAddress1Second {
            get {
                return ResourceManager.GetString("otherparties_correspondingAddress1Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence Address 2.
        /// </summary>
        internal static string otherparties_correspondingAddress2First {
            get {
                return ResourceManager.GetString("otherparties_correspondingAddress2First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string otherparties_correspondingAddress2Second {
            get {
                return ResourceManager.GetString("otherparties_correspondingAddress2Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string otherparties_email {
            get {
                return ResourceManager.GetString("otherparties_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string otherparties_fax {
            get {
                return ResourceManager.GetString("otherparties_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEnable.
        /// </summary>
        internal static string otherparties_isEnable {
            get {
                return ResourceManager.GetString("otherparties_isEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Party Name.
        /// </summary>
        internal static string otherparties_otherPartiesName {
            get {
                return ResourceManager.GetString("otherparties_otherPartiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Party No..
        /// </summary>
        internal static string otherparties_otherPartiesNum {
            get {
                return ResourceManager.GetString("otherparties_otherPartiesNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string otherparties_tel {
            get {
                return ResourceManager.GetString("otherparties_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Name.
        /// </summary>
        internal static string outgoingagent_agentName {
            get {
                return ResourceManager.GetString("outgoingagent_agentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent No..
        /// </summary>
        internal static string outgoingagent_agentNum {
            get {
                return ResourceManager.GetString("outgoingagent_agentNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string outgoingagent_contactPerson {
            get {
                return ResourceManager.GetString("outgoingagent_contactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence Address 1.
        /// </summary>
        internal static string outgoingagent_correspondingAddress1First {
            get {
                return ResourceManager.GetString("outgoingagent_correspondingAddress1First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string outgoingagent_correspondingAddress1Second {
            get {
                return ResourceManager.GetString("outgoingagent_correspondingAddress1Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence Address 2.
        /// </summary>
        internal static string outgoingagent_correspondingAddress2First {
            get {
                return ResourceManager.GetString("outgoingagent_correspondingAddress2First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string outgoingagent_correspondingAddress2Second {
            get {
                return ResourceManager.GetString("outgoingagent_correspondingAddress2Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence Address 3.
        /// </summary>
        internal static string outgoingagent_correspondingAddress3First {
            get {
                return ResourceManager.GetString("outgoingagent_correspondingAddress3First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string outgoingagent_correspondingAddress3Second {
            get {
                return ResourceManager.GetString("outgoingagent_correspondingAddress3Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string outgoingagent_email {
            get {
                return ResourceManager.GetString("outgoingagent_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string outgoingagent_fax {
            get {
                return ResourceManager.GetString("outgoingagent_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string outgoingagent_tel {
            get {
                return ResourceManager.GetString("outgoingagent_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string pricing_detailsDescription {
            get {
                return ResourceManager.GetString("pricing_detailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        internal static string pricing_priceValue {
            get {
                return ResourceManager.GetString("pricing_priceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Category.
        /// </summary>
        internal static string pricing_PricingType {
            get {
                return ResourceManager.GetString("pricing_PricingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string pricing_typeDescription {
            get {
                return ResourceManager.GetString("pricing_typeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Category.
        /// </summary>
        internal static string pricing_typeName {
            get {
                return ResourceManager.GetString("pricing_typeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        internal static string refer_billingAddressFirst {
            get {
                return ResourceManager.GetString("refer_billingAddressFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string refer_billingAddressSecond {
            get {
                return ResourceManager.GetString("refer_billingAddressSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string refer_contactPerson {
            get {
                return ResourceManager.GetString("refer_contactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence Address 1.
        /// </summary>
        internal static string refer_correspondingAddress1First {
            get {
                return ResourceManager.GetString("refer_correspondingAddress1First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string refer_correspondingAddress1Second {
            get {
                return ResourceManager.GetString("refer_correspondingAddress1Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence Address 2.
        /// </summary>
        internal static string refer_correspondingAddress2First {
            get {
                return ResourceManager.GetString("refer_correspondingAddress2First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string refer_correspondingAddress2Second {
            get {
                return ResourceManager.GetString("refer_correspondingAddress2Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string refer_email {
            get {
                return ResourceManager.GetString("refer_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string refer_fax {
            get {
                return ResourceManager.GetString("refer_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Legal Aid.
        /// </summary>
        internal static string refer_islegalAid {
            get {
                return ResourceManager.GetString("refer_islegalAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing Agent.
        /// </summary>
        internal static string refer_OutgoingAgent {
            get {
                return ResourceManager.GetString("refer_OutgoingAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor Name.
        /// </summary>
        internal static string refer_refererName {
            get {
                return ResourceManager.GetString("refer_refererName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor No..
        /// </summary>
        internal static string refer_refererNum {
            get {
                return ResourceManager.GetString("refer_refererNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string refer_tel {
            get {
                return ResourceManager.GetString("refer_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type Name.
        /// </summary>
        internal static string type_name {
            get {
                return ResourceManager.GetString("type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type No..
        /// </summary>
        internal static string type_num {
            get {
                return ResourceManager.GetString("type_num", resourceCulture);
            }
        }
    }
}
