'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class master
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.master", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy From Outgoing Agent.
        '''</summary>
        Friend Shared ReadOnly Property clientCopyFormOutgoingAgent() As String
            Get
                Return ResourceManager.GetString("clientCopyFormOutgoingAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy From Instructor.
        '''</summary>
        Friend Shared ReadOnly Property clientCopyFormReferer() As String
            Get
                Return ResourceManager.GetString("clientCopyFormReferer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remarks.
        '''</summary>
        Friend Shared ReadOnly Property clientRemarks() As String
            Get
                Return ResourceManager.GetString("clientRemarks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Group.
        '''</summary>
        Friend Shared ReadOnly Property client_accountGroup() As String
            Get
                Return ResourceManager.GetString("client_accountGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Billing Address.
        '''</summary>
        Friend Shared ReadOnly Property client_billingAddressFirst() As String
            Get
                Return ResourceManager.GetString("client_billingAddressFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property client_billingAddressSecond() As String
            Get
                Return ResourceManager.GetString("client_billingAddressSecond", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Billing Email.
        '''</summary>
        Friend Shared ReadOnly Property client_billingEmail() As String
            Get
                Return ResourceManager.GetString("client_billingEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client Name.
        '''</summary>
        Friend Shared ReadOnly Property client_clientName() As String
            Get
                Return ResourceManager.GetString("client_clientName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client No..
        '''</summary>
        Friend Shared ReadOnly Property client_clientNum() As String
            Get
                Return ResourceManager.GetString("client_clientNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson() As String
            Get
                Return ResourceManager.GetString("client_contactPerson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 02.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson02() As String
            Get
                Return ResourceManager.GetString("client_contactPerson02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 03.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson03() As String
            Get
                Return ResourceManager.GetString("client_contactPerson03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 04.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson04() As String
            Get
                Return ResourceManager.GetString("client_contactPerson04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 05.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson05() As String
            Get
                Return ResourceManager.GetString("client_contactPerson05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 06.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson06() As String
            Get
                Return ResourceManager.GetString("client_contactPerson06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 07.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson07() As String
            Get
                Return ResourceManager.GetString("client_contactPerson07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 08.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson08() As String
            Get
                Return ResourceManager.GetString("client_contactPerson08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 09.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson09() As String
            Get
                Return ResourceManager.GetString("client_contactPerson09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 10.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson10() As String
            Get
                Return ResourceManager.GetString("client_contactPerson10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 11.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson11() As String
            Get
                Return ResourceManager.GetString("client_contactPerson11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 12.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson12() As String
            Get
                Return ResourceManager.GetString("client_contactPerson12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 13.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson13() As String
            Get
                Return ResourceManager.GetString("client_contactPerson13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 14.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson14() As String
            Get
                Return ResourceManager.GetString("client_contactPerson14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 15.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson15() As String
            Get
                Return ResourceManager.GetString("client_contactPerson15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 16.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson16() As String
            Get
                Return ResourceManager.GetString("client_contactPerson16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 17.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson17() As String
            Get
                Return ResourceManager.GetString("client_contactPerson17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 18.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson18() As String
            Get
                Return ResourceManager.GetString("client_contactPerson18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 19.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson19() As String
            Get
                Return ResourceManager.GetString("client_contactPerson19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person 20.
        '''</summary>
        Friend Shared ReadOnly Property client_contactPerson20() As String
            Get
                Return ResourceManager.GetString("client_contactPerson20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correspondence Address 1.
        '''</summary>
        Friend Shared ReadOnly Property client_correspondingAddress1First() As String
            Get
                Return ResourceManager.GetString("client_correspondingAddress1First", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property client_correspondingAddress1Second() As String
            Get
                Return ResourceManager.GetString("client_correspondingAddress1Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correspondence Address 2.
        '''</summary>
        Friend Shared ReadOnly Property client_correspondingAddress2First() As String
            Get
                Return ResourceManager.GetString("client_correspondingAddress2First", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property client_correspondingAddress2Second() As String
            Get
                Return ResourceManager.GetString("client_correspondingAddress2Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discount(%).
        '''</summary>
        Friend Shared ReadOnly Property client_discount() As String
            Get
                Return ResourceManager.GetString("client_discount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Friend Shared ReadOnly Property client_email() As String
            Get
                Return ResourceManager.GetString("client_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 02.
        '''</summary>
        Friend Shared ReadOnly Property client_email02() As String
            Get
                Return ResourceManager.GetString("client_email02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 03.
        '''</summary>
        Friend Shared ReadOnly Property client_email03() As String
            Get
                Return ResourceManager.GetString("client_email03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 04.
        '''</summary>
        Friend Shared ReadOnly Property client_email04() As String
            Get
                Return ResourceManager.GetString("client_email04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 05.
        '''</summary>
        Friend Shared ReadOnly Property client_email05() As String
            Get
                Return ResourceManager.GetString("client_email05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 06.
        '''</summary>
        Friend Shared ReadOnly Property client_email06() As String
            Get
                Return ResourceManager.GetString("client_email06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 07.
        '''</summary>
        Friend Shared ReadOnly Property client_email07() As String
            Get
                Return ResourceManager.GetString("client_email07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 08.
        '''</summary>
        Friend Shared ReadOnly Property client_email08() As String
            Get
                Return ResourceManager.GetString("client_email08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 09.
        '''</summary>
        Friend Shared ReadOnly Property client_email09() As String
            Get
                Return ResourceManager.GetString("client_email09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 10.
        '''</summary>
        Friend Shared ReadOnly Property client_email10() As String
            Get
                Return ResourceManager.GetString("client_email10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 11.
        '''</summary>
        Friend Shared ReadOnly Property client_email11() As String
            Get
                Return ResourceManager.GetString("client_email11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 12.
        '''</summary>
        Friend Shared ReadOnly Property client_email12() As String
            Get
                Return ResourceManager.GetString("client_email12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 13.
        '''</summary>
        Friend Shared ReadOnly Property client_email13() As String
            Get
                Return ResourceManager.GetString("client_email13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 14.
        '''</summary>
        Friend Shared ReadOnly Property client_email14() As String
            Get
                Return ResourceManager.GetString("client_email14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 15.
        '''</summary>
        Friend Shared ReadOnly Property client_email15() As String
            Get
                Return ResourceManager.GetString("client_email15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 16.
        '''</summary>
        Friend Shared ReadOnly Property client_email16() As String
            Get
                Return ResourceManager.GetString("client_email16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 17.
        '''</summary>
        Friend Shared ReadOnly Property client_email17() As String
            Get
                Return ResourceManager.GetString("client_email17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 18.
        '''</summary>
        Friend Shared ReadOnly Property client_email18() As String
            Get
                Return ResourceManager.GetString("client_email18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 19.
        '''</summary>
        Friend Shared ReadOnly Property client_email19() As String
            Get
                Return ResourceManager.GetString("client_email19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email 20.
        '''</summary>
        Friend Shared ReadOnly Property client_email20() As String
            Get
                Return ResourceManager.GetString("client_email20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fax.
        '''</summary>
        Friend Shared ReadOnly Property client_fax() As String
            Get
                Return ResourceManager.GetString("client_fax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IO No.
        '''</summary>
        Friend Shared ReadOnly Property client_ioNumOfReferer() As String
            Get
                Return ResourceManager.GetString("client_ioNumOfReferer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Release To Public.
        '''</summary>
        Friend Shared ReadOnly Property client_isReleaseToPublic() As String
            Get
                Return ResourceManager.GetString("client_isReleaseToPublic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instructor.
        '''</summary>
        Friend Shared ReadOnly Property client_Referer() As String
            Get
                Return ResourceManager.GetString("client_Referer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ref No.
        '''</summary>
        Friend Shared ReadOnly Property client_refNumOfReferer() As String
            Get
                Return ResourceManager.GetString("client_refNumOfReferer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone.
        '''</summary>
        Friend Shared ReadOnly Property client_tel() As String
            Get
                Return ResourceManager.GetString("client_tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 02.
        '''</summary>
        Friend Shared ReadOnly Property client_tel02() As String
            Get
                Return ResourceManager.GetString("client_tel02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 03.
        '''</summary>
        Friend Shared ReadOnly Property client_tel03() As String
            Get
                Return ResourceManager.GetString("client_tel03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 04.
        '''</summary>
        Friend Shared ReadOnly Property client_tel04() As String
            Get
                Return ResourceManager.GetString("client_tel04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 05.
        '''</summary>
        Friend Shared ReadOnly Property client_tel05() As String
            Get
                Return ResourceManager.GetString("client_tel05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 06.
        '''</summary>
        Friend Shared ReadOnly Property client_tel06() As String
            Get
                Return ResourceManager.GetString("client_tel06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 07.
        '''</summary>
        Friend Shared ReadOnly Property client_tel07() As String
            Get
                Return ResourceManager.GetString("client_tel07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 08.
        '''</summary>
        Friend Shared ReadOnly Property client_tel08() As String
            Get
                Return ResourceManager.GetString("client_tel08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 09.
        '''</summary>
        Friend Shared ReadOnly Property client_tel09() As String
            Get
                Return ResourceManager.GetString("client_tel09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 10.
        '''</summary>
        Friend Shared ReadOnly Property client_tel10() As String
            Get
                Return ResourceManager.GetString("client_tel10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 11.
        '''</summary>
        Friend Shared ReadOnly Property client_tel11() As String
            Get
                Return ResourceManager.GetString("client_tel11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 12.
        '''</summary>
        Friend Shared ReadOnly Property client_tel12() As String
            Get
                Return ResourceManager.GetString("client_tel12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 13.
        '''</summary>
        Friend Shared ReadOnly Property client_tel13() As String
            Get
                Return ResourceManager.GetString("client_tel13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 14.
        '''</summary>
        Friend Shared ReadOnly Property client_tel14() As String
            Get
                Return ResourceManager.GetString("client_tel14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 15.
        '''</summary>
        Friend Shared ReadOnly Property client_tel15() As String
            Get
                Return ResourceManager.GetString("client_tel15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 16.
        '''</summary>
        Friend Shared ReadOnly Property client_tel16() As String
            Get
                Return ResourceManager.GetString("client_tel16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 17.
        '''</summary>
        Friend Shared ReadOnly Property client_tel17() As String
            Get
                Return ResourceManager.GetString("client_tel17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 18.
        '''</summary>
        Friend Shared ReadOnly Property client_tel18() As String
            Get
                Return ResourceManager.GetString("client_tel18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 19.
        '''</summary>
        Friend Shared ReadOnly Property client_tel19() As String
            Get
                Return ResourceManager.GetString("client_tel19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone 20.
        '''</summary>
        Friend Shared ReadOnly Property client_tel20() As String
            Get
                Return ResourceManager.GetString("client_tel20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Update Name.
        '''</summary>
        Friend Shared ReadOnly Property client_UpdateByUserName() As String
            Get
                Return ResourceManager.GetString("client_UpdateByUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Update Date.
        '''</summary>
        Friend Shared ReadOnly Property client_UpdateDate() As String
            Get
                Return ResourceManager.GetString("client_UpdateDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currency Name.
        '''</summary>
        Friend Shared ReadOnly Property currency_currencyName() As String
            Get
                Return ResourceManager.GetString("currency_currencyName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exchange Rate To HKD.
        '''</summary>
        Friend Shared ReadOnly Property currency_rateToHK() As String
            Get
                Return ResourceManager.GetString("currency_rateToHK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Symbol.
        '''</summary>
        Friend Shared ReadOnly Property currency_symbol() As String
            Get
                Return ResourceManager.GetString("currency_symbol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property keyword_description() As String
            Get
                Return ResourceManager.GetString("keyword_description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property keyword_name() As String
            Get
                Return ResourceManager.GetString("keyword_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Billing Address.
        '''</summary>
        Friend Shared ReadOnly Property otherparties_billingAddressFirst() As String
            Get
                Return ResourceManager.GetString("otherparties_billingAddressFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property otherparties_billingAddressSecond() As String
            Get
                Return ResourceManager.GetString("otherparties_billingAddressSecond", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person.
        '''</summary>
        Friend Shared ReadOnly Property otherparties_contactPerson() As String
            Get
                Return ResourceManager.GetString("otherparties_contactPerson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correspondence Address 1.
        '''</summary>
        Friend Shared ReadOnly Property otherparties_correspondingAddress1First() As String
            Get
                Return ResourceManager.GetString("otherparties_correspondingAddress1First", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property otherparties_correspondingAddress1Second() As String
            Get
                Return ResourceManager.GetString("otherparties_correspondingAddress1Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correspondence Address 2.
        '''</summary>
        Friend Shared ReadOnly Property otherparties_correspondingAddress2First() As String
            Get
                Return ResourceManager.GetString("otherparties_correspondingAddress2First", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property otherparties_correspondingAddress2Second() As String
            Get
                Return ResourceManager.GetString("otherparties_correspondingAddress2Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Friend Shared ReadOnly Property otherparties_email() As String
            Get
                Return ResourceManager.GetString("otherparties_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fax.
        '''</summary>
        Friend Shared ReadOnly Property otherparties_fax() As String
            Get
                Return ResourceManager.GetString("otherparties_fax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IsEnable.
        '''</summary>
        Friend Shared ReadOnly Property otherparties_isEnable() As String
            Get
                Return ResourceManager.GetString("otherparties_isEnable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Party Name.
        '''</summary>
        Friend Shared ReadOnly Property otherparties_otherPartiesName() As String
            Get
                Return ResourceManager.GetString("otherparties_otherPartiesName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Party No..
        '''</summary>
        Friend Shared ReadOnly Property otherparties_otherPartiesNum() As String
            Get
                Return ResourceManager.GetString("otherparties_otherPartiesNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone.
        '''</summary>
        Friend Shared ReadOnly Property otherparties_tel() As String
            Get
                Return ResourceManager.GetString("otherparties_tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agent Name.
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_agentName() As String
            Get
                Return ResourceManager.GetString("outgoingagent_agentName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agent No..
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_agentNum() As String
            Get
                Return ResourceManager.GetString("outgoingagent_agentNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person.
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_contactPerson() As String
            Get
                Return ResourceManager.GetString("outgoingagent_contactPerson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correspondence Address 1.
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_correspondingAddress1First() As String
            Get
                Return ResourceManager.GetString("outgoingagent_correspondingAddress1First", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_correspondingAddress1Second() As String
            Get
                Return ResourceManager.GetString("outgoingagent_correspondingAddress1Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correspondence Address 2.
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_correspondingAddress2First() As String
            Get
                Return ResourceManager.GetString("outgoingagent_correspondingAddress2First", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_correspondingAddress2Second() As String
            Get
                Return ResourceManager.GetString("outgoingagent_correspondingAddress2Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correspondence Address 3.
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_correspondingAddress3First() As String
            Get
                Return ResourceManager.GetString("outgoingagent_correspondingAddress3First", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_correspondingAddress3Second() As String
            Get
                Return ResourceManager.GetString("outgoingagent_correspondingAddress3Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_email() As String
            Get
                Return ResourceManager.GetString("outgoingagent_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fax.
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_fax() As String
            Get
                Return ResourceManager.GetString("outgoingagent_fax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone.
        '''</summary>
        Friend Shared ReadOnly Property outgoingagent_tel() As String
            Get
                Return ResourceManager.GetString("outgoingagent_tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property pricing_detailsDescription() As String
            Get
                Return ResourceManager.GetString("pricing_detailsDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fees.
        '''</summary>
        Friend Shared ReadOnly Property pricing_priceValue() As String
            Get
                Return ResourceManager.GetString("pricing_priceValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Work Category.
        '''</summary>
        Friend Shared ReadOnly Property pricing_PricingType() As String
            Get
                Return ResourceManager.GetString("pricing_PricingType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property pricing_typeDescription() As String
            Get
                Return ResourceManager.GetString("pricing_typeDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Work Category.
        '''</summary>
        Friend Shared ReadOnly Property pricing_typeName() As String
            Get
                Return ResourceManager.GetString("pricing_typeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Billing Address.
        '''</summary>
        Friend Shared ReadOnly Property refer_billingAddressFirst() As String
            Get
                Return ResourceManager.GetString("refer_billingAddressFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property refer_billingAddressSecond() As String
            Get
                Return ResourceManager.GetString("refer_billingAddressSecond", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Person.
        '''</summary>
        Friend Shared ReadOnly Property refer_contactPerson() As String
            Get
                Return ResourceManager.GetString("refer_contactPerson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correspondence Address 1.
        '''</summary>
        Friend Shared ReadOnly Property refer_correspondingAddress1First() As String
            Get
                Return ResourceManager.GetString("refer_correspondingAddress1First", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property refer_correspondingAddress1Second() As String
            Get
                Return ResourceManager.GetString("refer_correspondingAddress1Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correspondence Address 2.
        '''</summary>
        Friend Shared ReadOnly Property refer_correspondingAddress2First() As String
            Get
                Return ResourceManager.GetString("refer_correspondingAddress2First", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property refer_correspondingAddress2Second() As String
            Get
                Return ResourceManager.GetString("refer_correspondingAddress2Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Friend Shared ReadOnly Property refer_email() As String
            Get
                Return ResourceManager.GetString("refer_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fax.
        '''</summary>
        Friend Shared ReadOnly Property refer_fax() As String
            Get
                Return ResourceManager.GetString("refer_fax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is Legal Aid.
        '''</summary>
        Friend Shared ReadOnly Property refer_islegalAid() As String
            Get
                Return ResourceManager.GetString("refer_islegalAid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Outgoing Agent.
        '''</summary>
        Friend Shared ReadOnly Property refer_OutgoingAgent() As String
            Get
                Return ResourceManager.GetString("refer_OutgoingAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instructor Name.
        '''</summary>
        Friend Shared ReadOnly Property refer_refererName() As String
            Get
                Return ResourceManager.GetString("refer_refererName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instructor No..
        '''</summary>
        Friend Shared ReadOnly Property refer_refererNum() As String
            Get
                Return ResourceManager.GetString("refer_refererNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone.
        '''</summary>
        Friend Shared ReadOnly Property refer_tel() As String
            Get
                Return ResourceManager.GetString("refer_tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Type Name.
        '''</summary>
        Friend Shared ReadOnly Property type_name() As String
            Get
                Return ResourceManager.GetString("type_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Type No..
        '''</summary>
        Friend Shared ReadOnly Property type_num() As String
            Get
                Return ResourceManager.GetString("type_num", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
